### ISSUE TITLE
Error "Invalid search bound (wrong side of point)"

### ISSUE THREAD

**Issue by nohzafk** [localauthor/org-side-tree#19]
When invoking the function `org-side-tree`, an error "Invalid search bound (wrong side of point)" is frequently encountered. As a result, the side window fails to open. On occasions where the side window does open, modifying the file often reproduces the error, causing instability.

## Steps to Reproduce
1. Open an Org-mode file.
2. Invoke the function `org-side-tree`.
3. Observe the error message: "Invalid search bound (wrong side of point)".
4. In some cases, the side window may open successfully.
5. Modify the Org file (e.g., add or edit headings, src blocks).
6. Note that the error may reoccur, causing inconsistent behavior with the side window.

## Debug Information
- The error is thrown inside the function `org-side-tree-get-headings`.
- In the code segment:
  ```elisp
  (while (re-search-forward heading-regexp nil t)
    (let* ((beg (line-beginning-position))
           (end (line-end-position))
           (heading
            (or (and (and org-side-tree-add-overlays
                          (derived-mode-p 'org-mode))
                     (org-side-tree-overlays-to-text beg end))
                (org-side-tree-buffer-substring beg end))))
  ```
- The function `org-side-tree-overlays-to-text` is responsible for the error, especially when `beg` and `end` positions include a src block.

## Environment
- **Org-mode version**: doom emacs
- **Emacs version**: emacs-plus@29
- **Operating System**: MacOS

## Additional Information
The error seems to be related to the presence of src blocks within the `beg` and `end` positions passed to the function `org-side-tree-overlays-to-text`.

**Comment by localauthor** [comment]
Thanks for the detailed report. I cannot reproduce it, so could you provide more details about the file that raises the error? Or could you share a file that I could use to try to reproduce the issue (with sensitive info taken out, of course)?

**Comment by localauthor** [comment]
> ## Additional Information
> The error seems to be related to the presence of src blocks within the `beg` and `end` positions passed to the function `org-side-tree-overlays-to-text`.

This part doesn't make sense to me.

The `beg` and `end` positions should be the beginning and end of a heading. So it shouldn't be possible for there to be a src block _between_ `beg` and `end`.

Have you modified `outline-regexp` in some way?

**Comment by localauthor** [comment]
I think I see the problem. Does the error occur when all headlines are unfolded?

I don't know how to fix this yet, but I would suggest setting `org-side-tree-add-overlays` to nil for the time being.

**Comment by localauthor** [comment]
Just pushed a change, let me know if it help

**Comment by localauthor** [comment]
Just pushed a change, let me know if it helps

**Comment by nohzafk** [comment]
Thanks! I've tested it. With the latest commit, the side tree can be opened.

However, if I turn on the debugger using `M-x toggle-debug-on-error`, the error still pops up **after I click** the heading on the org-side-tree buffer. This time, it doesn't affect usage. So i think i just turn off the debugger is OK, the error message is for your reference.

Here is the screenshot. The "beg" point reported at the error message is actually at the next line of the heading.

<img width="1483" alt="image" src="https://github.com/localauthor/org-side-tree/assets/149959021/39d6e8d5-f5b3-49e1-ba5b-f47d1e60297d">

**Comment by nohzafk** [comment]
also i found out that if the org-side-tree window is opend at the `right` side, the error still happens and the window won't open. situation of `left` side is described above.

**Comment by sjLambda** [comment]
I get the same error behavior except that my setup is a linux, emacs is the latest compilation from master branch of the trunk with native compilation turned on, and the org files are both small and large. I've not noticed any difference in the folded/unfolded state. Sometimes the side window opens but is empty.

**Comment by bitozoid** [comment]
In my case, Doom Emacs and Emacs 30.1, it seems that I need not to be on a header. Otherwise it fails with this error.

**Comment by Glider-P90** [comment]
Hello, it's my first time, i've fixed an issue on github, so i hope i'm in good direction.
I did fork the project and i pushed it, but not sur you see the correction, hope so.
Just waiting for your return to confim if you receive the fix for this issue.
PS: Sorry for my english, Have fun from France.

**Comment by localauthor** [comment]
Thanks for the contribution. Since I couldn’t reproduce the issue, I can’t confirm the fix. Maybe someone who reported can confirm this works?

________________________________

**Comment by bitozoid** [comment]
My report using Doom Emacs.

**1. Version from MELPA (with org 9.8)**: The error still appears.

**2. Patched version**: The previous error does not appear anymore. Moreover, the side tree gets updated on every change in the tree of headers in the original buffer.

**But then, I realized that I had not upgraded Doom Emacs. So I did.**

```
...
   ✓ (114/215) org: 89df5bf -> c1bb5ae [24 commit(s)] (w/ 17 dependents)
        c1bb5ae59 Update version number for the 9.8.1 release
        09c585c60 org-fold-core: Update commentary for renamed function
        13e035072 org-fold-core: Rename another function for American spelling
        849f24982 Fix incorrect values of :safe t and :safe nil
        e01282323 etc/ORG-NEWS: Fix typo
        be7ad3124 ob-csharp: Fix a defcustom type
        1cbeb7f85 lisp/org.el: Address compiler warnings from Emacs master
        cf141e8a0 org-timer-set-timer: Fix when called from org-agenda on entry without EFFORT
        e2ef50603 org-assert-version: Add another suggestion how to fix version mismatch
        bbcf95331 Account that latexmk requires perl to work
        cedc089b7 ob-emacs-lisp: Accept :lexical t with t being a symbol
        df7f1dd02 org-table-beginning-of-field, org-table-end-of-field: Fix argument list
        f75579b2c lisp/org.el: Name manual in respective menu entry
        f8de8cf72 Fix org-set-font-lock-defaults priority cookie regular expression
        7512a60b3 Clean up spacing to pass Emacs's pre-commit check
        573e2435a etc/ORG-NEWS: Fix another code example
        4241dd3fe etc/ORG-NEWS: Fix typo in markup
        1b237357c etc/ORG-NEWS: Fix another code example
        4cf2b36c6 etc/ORG-NEWS: Fix code example
        e0ef255b5 etc/ORG-NEWS: Fix another broken link
        [...]
```

that corresponds to upgrade from 9.8 to 9.8.1 (updated FOUR days ago). See https://cgit.git.savannah.nongnu.org/cgit/org-mode.git/log/?qt=range&q=c1bb5ae

**3. MELPA Version with org 9.8.1**. The error does not appear any more.

Other packages have also been updated for my setup (34), but I guess that the most important is the org package (I can't see any other relevant from the logs).

@Glider-P90 What version of org-mode are you running?

**Comment by Glider-P90** [comment]
My org version is under yours.

Package org is built-in.    Version: 9.7.11
